site_name: Dino
pages:
    - Home: index.md
    - Installation: md/installation.md
    - Getting Started: md/getting_started.md
    - Usage: md/usage.md
    - API: md/api.md
    - Web UI API: md/web.md
    - Events: md/events.md
    - External Events: md/external_events.md
    - ACL: md/acl.md
    - REST API: md/rest.md
    - Who Is Online?: md/wio.md
    - Storage: md/storage.md
theme: readthedocs
